version: '3.9'
services:

  postgres:
    image: postgres:16.0-alpine3.17
    environment:
      POSTGRES_USER: "blog"
      POSTGRES_PASSWORD: "blog"
      POSTGRES_DB: "blog"
    ports:
      - "5432:5432"
