spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/blog
    username: blog
    password: blog
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/blog
    user: blog
    password: blog

server:
  port: 8070

code-api-client:
  host: http://localhost:8020
