spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: blog
    password: blog
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true

server:
  port: 8060
  error:
    include-message: always
    whitelabel:
      enabled: false

code-api-client:
  host: http://localhost:8020

